# Config Mosquitto pour le test du worker app:mqtt:subscribe
listener 1883

# Auth : ton worker se connecte avec MQTT_USER / MQTT_PASSWORD.
# Le fichier passwd est généré dans le Dockerfile.
allow_anonymous false
password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/
log_dest stdout
