<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260707145100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alert (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, email_sent BOOLEAN NOT NULL, warehouse_id INT NOT NULL, batch_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17FD46C15080ECDE ON alert (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_17FD46C1F39EBE7A ON alert (batch_id)');
        $this->addSql('CREATE TABLE batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ref VARCHAR(255) NOT NULL, storage_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, exploitation_id INT NOT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F80B52D4D967A16D ON batch (exploitation_id)');
        $this->addSql('CREATE INDEX IDX_F80B52D45080ECDE ON batch (warehouse_id)');
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, iso_code VARCHAR(255) NOT NULL, ideal_temp DOUBLE PRECISION NOT NULL, ideal_humidity DOUBLE PRECISION NOT NULL, tolerance_temp DOUBLE PRECISION NOT NULL, tolerance_humidity DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exploitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BEBCFB1F92F3E70 ON exploitation (country_id)');
        $this->addSql('CREATE TABLE measure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, temperature DOUBLE PRECISION DEFAULT NULL, humidity DOUBLE PRECISION DEFAULT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sensor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80071925A247991F ON measure (sensor_id)');
        $this->addSql('CREATE TABLE responsible (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97E625E8F92F3E70 ON responsible (country_id)');
        $this->addSql('CREATE TABLE sensor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hardware_id VARCHAR(255) NOT NULL, model VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, last_com DATE NOT NULL, warehouse_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC8617B05080ECDE ON sensor (warehouse_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE warehouse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECB38BFCF92F3E70 ON warehouse (country_id)');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C15080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alert ADD CONSTRAINT FK_17FD46C1F39EBE7A FOREIGN KEY (batch_id) REFERENCES batch (id)');
        $this->addSql('ALTER TABLE batch ADD CONSTRAINT FK_F80B52D4D967A16D FOREIGN KEY (exploitation_id) REFERENCES exploitation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE batch ADD CONSTRAINT FK_F80B52D45080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exploitation ADD CONSTRAINT FK_BEBCFB1F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measure ADD CONSTRAINT FK_80071925A247991F FOREIGN KEY (sensor_id) REFERENCES sensor (id)');
        $this->addSql('ALTER TABLE responsible ADD CONSTRAINT FK_97E625E8F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sensor ADD CONSTRAINT FK_BC8617B05080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C15080ECDE');
        $this->addSql('ALTER TABLE alert DROP CONSTRAINT FK_17FD46C1F39EBE7A');
        $this->addSql('ALTER TABLE batch DROP CONSTRAINT FK_F80B52D4D967A16D');
        $this->addSql('ALTER TABLE batch DROP CONSTRAINT FK_F80B52D45080ECDE');
        $this->addSql('ALTER TABLE exploitation DROP CONSTRAINT FK_BEBCFB1F92F3E70');
        $this->addSql('ALTER TABLE measure DROP CONSTRAINT FK_80071925A247991F');
        $this->addSql('ALTER TABLE responsible DROP CONSTRAINT FK_97E625E8F92F3E70');
        $this->addSql('ALTER TABLE sensor DROP CONSTRAINT FK_BC8617B05080ECDE');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCF92F3E70');
        $this->addSql('DROP TABLE alert');
        $this->addSql('DROP TABLE batch');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE exploitation');
        $this->addSql('DROP TABLE measure');
        $this->addSql('DROP TABLE responsible');
        $this->addSql('DROP TABLE sensor');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE warehouse');
    }
}
