; PlatformIO project — FutureKawa IoT module (NodeMCU ESP8266 + DHT11)
; Docs: https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
    256dpi/MQTT@^2.5
    beegee-tokyo/DHTesp@^1.19
    bblanchon/ArduinoJson@^7
